# .github/workflows/release.yml
name: Notify Release on Publish

on:
  release:
    types: [published]

jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Release to Discord
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_RELEASE }} \
            -H "Content-Type: application/json" \
            -d '{
              "username": "Release Bot",
              "content": "📦 **새 릴리즈: `${{ github.event.release.tag_name }}`**\n🔗 ${{ github.event.release.html_url }}"
            }'
